### ISSUE TITLE
Irrelevant "HackTools" image on README

### ISSUE THREAD

**Issue by PinkDev1** [r00t-3xp10it/redpill#7]
I thought this tool would have some kind of web interface. Why is there an image of a completely unrelated project, on the very top of the README? Seems deceiving.

**Comment by r00t-3xp10it** [comment]
if you had spent some time reading the project description maybe you would not have jumped to conclusions ...
because in the description I never mentioned that it was a tool with <b><i>GUI's</i></b> or <b><i>web interfaces</i></b> ...

<b><i>'it clearly says that it is a project to be run in a '''reverse tcp shell prompt''' ... </i></b>
1º - i even have published\recoded video tutorials that shows the tool working,
2º - there are even screenshots demonstrating how the tool operates .....
.
All of this could be avoided if you have spend so time reading the readme file ...
![maybee](https://user-images.githubusercontent.com/23490060/124057633-c4786d00-da1f-11eb-841f-61bf87f5596e.png)
